[platformio]
src_dir = .

[env:teensy41]
platform         = teensy
board            = teensy41
framework        = arduino
upload_protocol  = teensy-cli

; USB serial for Teensy Loader and Serial comms
build_flags = -DUSB_SERIAL

monitor_speed = 115200
