[env:teensy41]
platform  = teensy
board     = teensy41
framework = arduino

; USB serial for Teensy Loader and Serial comms
build_flags = -DUSB_SERIAL

; Optional: raise serial baud in monitor
monitor_speed = 115200
